l_english:
 SETTING_INPUT_CONTEXT_COMMON:0 "Common"
 SETTING_INPUT_CONTEXT_COMMON_TOOLTIP:0 "Keybinds for the common input context"

 SETTING_INPUT_ACTION_PAUSE:0 "Pause / Unpause"
 SETTING_INPUT_ACTION_INCREASE_SPEED:0 "Increase Speed"
 SETTING_INPUT_ACTION_DECREASE_SPEED:0 "Decrease Speed"
 SETTING_INPUT_ACTION_SPEED_ONE:0 "Speed 1"
 SETTING_INPUT_ACTION_SPEED_TWO:0 "Speed 2"
 SETTING_INPUT_ACTION_SPEED_THREE:0 "Speed 3"
 SETTING_INPUT_ACTION_SPEED_FOUR:0 "Speed 4"
 SETTING_INPUT_ACTION_SPEED_FIVE:0 "Speed 5"
 SETTING_INPUT_ACTION_PLAY_PAUSE_MUSIC: "Play/Pause Music"
 SETTING_INPUT_ACTION_NEXT_MUSIC_TRACK: "Next Music track"
 SETTING_INPUT_ACTION_CAMERA_UP:0 "Pan Camera Up"
 SETTING_INPUT_ACTION_CAMERA_LEFT:0 "Pan Camera Left"
 SETTING_INPUT_ACTION_CAMERA_DOWN:0 "Pan Camera Down"
 SETTING_INPUT_ACTION_CAMERA_RIGHT:0 "Pan Camera Right"
 SETTING_INPUT_ACTION_LOCATION_FINDER: "Location Finder"
 SETTING_INPUT_ACTION_OPEN_POLITICS: "Politics"
 SETTING_INPUT_ACTION_OPEN_BUDGET: "Budget"
 SETTING_INPUT_ACTION_OPEN_BUILDINGS: "Buildings"
 SETTING_INPUT_ACTION_OPEN_MARKET: "Market"
 SETTING_INPUT_ACTION_OPEN_MILITARY: "Military"
 SETTING_INPUT_ACTION_OPEN_DIPLOMATIC: "Diplomatic"
 SETTING_INPUT_ACTION_OPEN_TECHNOLOGY: "Technology"
 SETTING_INPUT_ACTION_OPEN_CULTURE: "Culture"
 SETTING_INPUT_ACTION_OPEN_POPULATION: "Population"
 SETTING_INPUT_ACTION_OPEN_JOURNAL: "Journal"
 SETTING_INPUT_ACTION_OPEN_DECISIONS: "Decisions"
 SETTING_INPUT_ACTION_MAP_LIST: "Ledger"
 SETTING_INPUT_ACTION_BACK: "Back"
 SETTING_INPUT_ACTION_OPEN_OUTLINER: "Outliner"
 SETTING_INPUT_ACTION_TAB_1: "Tab 1"
 SETTING_INPUT_ACTION_TAB_2: "Tab 2"
 SETTING_INPUT_ACTION_TAB_3: "Tab 3"
 SETTING_INPUT_ACTION_TAB_4: "Tab 4"
 SETTING_INPUT_ACTION_TAB_5: "Tab 5"
 SETTING_INPUT_ACTION_PRODUCTION_LENS: "Production Lens"
 SETTING_INPUT_ACTION_POLITICAL_LENS: "Political Lens"
 SETTING_INPUT_ACTION_DIPLOMATIC_LENS: "Diplomatic Lens"
 SETTING_INPUT_ACTION_MILITARY_LENS: "Military Lens"
 SETTING_INPUT_ACTION_TRADE_LENS: "Trade Lens"
 SETTING_INPUT_ACTION_CONFIRM: "Confirm"
 SETTING_INPUT_ACTION_CURRENT_SITUATION: "Current Situation"
 SETTING_INPUT_ACTION_CONSTRUCTION_QUEUE: "Construction Queue"
 SETTING_INPUT_ACTION_GO_TO_DETAILS: "Go to Details"
 SETTING_INPUT_ACTION_SCROLL_UP: "Scroll up"
 SETTING_INPUT_ACTION_SCROLL_DOWN: "Scroll down"
 SETTING_INPUT_ACTION_TOGGLE_GUI_DEBUG: "(Debug) gui.debug"